site_name: Exercícios Perceptron
site_url: https://guiparaiso.github.io/Deep-Learning-Pages/
nav:
  - Home: index.md
  - Perceptron:
      - Exercise 1: perceptron/exercise1.md
      - Exercise 2: perceptron/exercise2.md
theme:
  name: material
